"""
Страница «Сервисы» (2026-10-05, просьба Alex): все внешние сервисы проекта — что даёт, какие API (коротко), как используем,
ключ в .env (только имя), цена; и подписки — сколько стоят и когда заканчиваются.
Список ведётся руками: новый сервис / ключ / подписка — допиши сюда (и в docs/ARCHITECTURE.md).
mode: "live" — работает по расписанию; "research" — только исследования / разово; "idle" — ключ есть, не используется.
"""

SERVICES = [
    ("Polymarket", [
        {"name": "Polymarket — маркеты", "site": "https://polymarket.com", "what": "список погодных маркетов, варианты, итоги",
         "apis": ["gamma-api.polymarket.com/events, /markets"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_edge, weather_poly_resolve, weather_sharp_rank"},
        {"name": "Polymarket — цены и стаканы", "site": "https://polymarket.com", "what": "цены, стаканы заявок, история цен — исполнение виртуальных ставок",
         "apis": ["clob.polymarket.com/book, /prices-history"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "polyexec, weather_paper, weather_obs_live, weather_obs_rt, weather_price_history"},
        {"name": "Polymarket — сделки и трейдеры", "site": "https://polymarket.com", "what": "все сделки погоды с кошельками, сделки трейдеров для повтора",
         "apis": ["data-api.polymarket.com/trades, /activity"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_trades_history, weather_copy, weather_mm_settle"},
        {"name": "Polymarket — живой поток", "site": "https://polymarket.com", "what": "стаканы и сделки в реальном времени: бот-мейкер, гонка после замера, свои стаканы, повтор за секунды",
         "apis": ["wss ws-subscriptions-clob …/ws/market", "wss ws-live-data (сделки)"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_mm_ws, weather_obs_rt, weather_copy_live"},
    ]),
    ("Прогнозы погоды", [
        {"name": "Open-Meteo", "site": "https://open-meteo.com", "what": "прогнозы ~16 моделей, ансамбли, прошлые прогнозы для обучения",
         "apis": ["api / ensemble-api", "previous-runs-api", "historical-forecast-api", "single-runs-api, satellite-api (исследования)"],
         "mode": "live", "key": None, "price": "бесплатно, ~10 тыс. вызовов/сутки (крон тратит 5-6 тыс.)",
         "scripts": "weather_edge, weather_ens, weather_multimodel, weather_ml_data, weather_llm_hour"},
        {"name": "Iowa Environmental Mesonet", "site": "https://mesonet.agron.iastate.edu", "what": "история METAR станций, NBM, LAMP, прогнозные обсуждения",
         "apis": ["mesonet.agron.iastate.edu/cgi-bin/request/asos.py, /api"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_station_obs, weather_ml_data, weather_night_check"},
    ]),
    ("Замеры станций", [
        {"name": "NOAA Aviation Weather", "site": "https://aviationweather.gov", "what": "сводки METAR всех аэропортов — факт, по которому решаются маркеты",
         "apis": ["aviationweather.gov/api/data/metar"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_obs_live, weather_obs_rt, weather_llm_hour, weather_ml_live"},
        {"name": "NOAA tgftp", "site": "https://tgftp.nws.noaa.gov", "what": "файлы METAR по станциям — самый быстрый бесплатный путь",
         "apis": ["tgftp.nws.noaa.gov/data/observations/metar/stations"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_obs_rt, weather_obs_wethr, weather_obs_live"},
        {"name": "wethr.net", "site": "https://wethr.net", "what": "поток замеров США быстрее NOAA (~48 с) — кошелёк obs_wethr",
         "apis": ["wethr.net REST + поток событий (SSE)"], "mode": "live", "key": "WETHR_API_KEY", "price": "$24.99/мес — см. подписки",
         "scripts": "weather_obs_wethr"},
        {"name": "Synoptic Data", "site": "https://synopticdata.com", "what": "5-минутные замеры аэропортов США — кошелёк obs_fast",
         "apis": ["api.synopticdata.com/v2/stations/latest"], "mode": "live", "key": "SYNOPTIC_TOKEN, SYNOPTIC_KEY", "price": "пробный доступ — см. подписки",
         "scripts": "weather_fastobs"},
        {"name": "Национальные службы", "site": None, "what": "быстрые замеры вне США: Финляндия (FMI), Япония (JMA), Германия (DWD), Нидерланды (KNMI), Гонконг (HKO)",
         "apis": ["opendata.fmi.fi", "jma.go.jp", "opendata.dwd.de", "api.dataplatform.knmi.nl", "data.weather.gov.hk"],
         "mode": "live", "key": "KNMI_API_KEY (только KNMI)", "price": "бесплатно", "scripts": "weather_fastobs, weather_obs_live"},
        {"name": "Канада, Турция, Польша", "site": None, "what": "свои быстрые ленты замеров: Environment Canada (SWOB), MGM, IMGW (Варшава)",
         "apis": ["dd.weather.gc.ca", "servis.mgm.gov.tr", "awiacja.imgw.pl"], "mode": "live", "key": None, "price": "бесплатно",
         "scripts": "weather_obs_rt"},
        {"name": "Netatmo", "site": "https://dev.netatmo.com", "what": "частные станции у аэропортов — только сбор для проверки",
         "apis": ["api.netatmo.com/api/getpublicdata"], "mode": "live", "key": "NETATMO_* (токен обновляется сам)", "price": "бесплатно",
         "scripts": "weather_netatmo"},
        {"name": "CWOP (народные станции)", "site": "http://www.wxqa.com", "what": "любительские станции США в 20 км от аэропортов — сбор истории",
         "apis": ["cwop.aprs.net:14580 (поток APRS)"], "mode": "live", "key": None, "price": "бесплатно", "scripts": "weather_pws_live"},
    ]),
    ("LLM", [
        {"name": "Google Gemini API (бесплатный уровень)", "site": "https://aistudio.google.com", "what": "Gemini для llm_gem напрямую (с 08.10): бесплатно только 20 запросов в сутки (лимит Free tier на проект и модель), остальные ~52 — через OpenRouter",
         "apis": ["generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent"], "mode": "live", "key": "GEMINI_API_KEY",
         "price": "бесплатно (Free tier; запросы Google может использовать для улучшения продуктов — личных данных в них нет)", "scripts": "weather_llm_hour"},
        {"name": "OpenRouter", "site": "https://openrouter.ai", "what": "LLM-прогноз каждый час: DeepSeek (llm_ds); Gemini — только запасной путь, если Google не ответил",
         "apis": ["openrouter.ai/api/v1/chat/completions"], "mode": "live", "key": "OPENROUTER_API_KEY", "price": "по расходу — см. подписки",
         "scripts": "weather_llm_hour"},
        {"name": "Ollama (свой сервер в сети)", "site": None, "what": "локальная Qwen3 для разбора прогнозных обсуждений — исследования",
         "apis": ["Ollama API в домашней сети"], "mode": "research", "key": None, "price": "бесплатно (свой компьютер)", "scripts": "weather_afd"},
    ]),
    ("Исследования и разовые проверки", [
        {"name": "Falcon (polymarketanalytics.com)", "site": "https://api.polymarketanalytics.com/dashboard", "what": "история стаканов Polymarket — проверка бота-мейкера; данные скачаны в data/research/falcon",
         "apis": ["narrative.agent.heisenberg.so …/retrieve/parameterized (agent 572)"], "mode": "research", "key": "PMA_TOKEN",
         "price": "$10 за 20 тыс. кредитов — см. подписки", "scripts": "weather_falcon_fetch, weather_study_falcon"},
        {"name": "Kalshi", "site": "https://kalshi.com", "what": "те же погодные маркеты на другой бирже — сравнение цен",
         "apis": ["api.elections.kalshi.com/trade-api/v2"], "mode": "research", "key": None, "price": "бесплатно",
         "scripts": "weather_kalshi_hist, weather_study_kalshi"},
        {"name": "Xweather", "site": "https://data.portal.xweather.com", "what": "частные станции (архив 1-мин с августа), METAR — проверено 01.10: медленнее нашего",
         "apis": ["data.api.xweather.com/observations"], "mode": "research", "key": "XWEATHER_CLIENT_ID, XWEATHER_CLIENT_SECRET",
         "price": "бесплатный тариф, 100 запросов/мин", "scripts": "data/research/xw_fetch.py, xw_mexico.py"},
        {"name": "Météo-France", "site": "https://portail-api.meteofrance.fr", "what": "6-мин замеры Ле-Бурже (Париж) — проверено 01.10: ~10 мин после замера, медленнее METAR",
         "apis": ["public-api.meteofrance.fr DPObs"], "mode": "research", "key": "METEOFRANCE_KEY, METEOFRANCE_KEY2", "price": "бесплатно",
         "scripts": "разовая проверка"},
        {"name": "AEMET (Испания), CWA (Тайвань)", "site": None, "what": "ключи получены для национальных замеров, в коде не используются",
         "apis": ["opendata.aemet.es", "opendata.cwa.gov.tw"], "mode": "idle", "key": "AEMET_API_KEY, CWA_API_KEY", "price": "бесплатно", "scripts": "—"},
    ]),
]

# status: "active" — действует и списывает деньги; "closed" — отменена; "trial" — пробная; "prepaid" — баланс по расходу.
# ends — дата окончания / следующего списания (ГГГГ-ММ-ДД) или None, если не знаем; checked — когда сведения сверены.
SUBSCRIPTIONS = [
    {"name": "wethr.net", "plan": "Professional", "price": "$24.99", "per": "в месяц", "monthly": 24.99, "status": "active",
     "since": "2026-10-01", "ends": "2026-11-01", "ends_label": "следующее списание",
     "note": "Решение 15.10 по порогу из PRD: на 05.10 опережение 48 с (нужно ≥ 1 мин), лишних денег ~$2.45 (нужно ≥ $25 за 14 дней). Отменить до 01.11, если не пройдёт.",
     "checked": "2026-10-05"},
    {"name": "Falcon (polymarketanalytics.com)", "plan": "20 000 кредитов", "price": "$10", "per": "разово", "monthly": 0.0, "status": "closed",
     "since": "2026-09-30", "ends": None, "ends_label": "закрыта 05.10",
     "note": "Осталось 1 220 кредитов (05.10). Стаканы теперь пишем сами (data/books); скачанное — data/research/falcon.",
     "checked": "2026-10-05"},
    {"name": "OpenRouter", "plan": "предоплата: баланс $16.70 на 08.10 (Alex пополнил на $10, всего внесено ≈$20)", "price": "по расходу", "per": "", "monthly": None, "status": "prepaid",
     "since": "2026-10-03", "ends": None, "ends_label": "пока есть баланс",
     "note": "Лимит в коде: llm_gem $13.5 + llm_ds $4 в месяц (с 08.10, октябрь — эксперимент) — дошёл до лимита, кошелёк пропускает часы до 1-го числа.",
     "checked": "2026-10-08", "openrouter": True},
    {"name": "Synoptic Data", "plan": "пробный доступ", "price": "$0", "per": "", "monthly": 0.0, "status": "trial",
     "since": "2026-09-30", "ends": None, "ends_label": "дата окончания неизвестна",
     "note": "Работает (05.10). Когда закончится — obs_fast останется без замеров США; платный тариф — решение Alex.",
     "checked": "2026-10-05"},
]
